apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello.yaml

resources:
  - namespace.yaml
  - deployment-hello-pod-anti-affinity-preferred.yaml
  - route-hello.yaml
  - service-hello.yaml
